"""Fixed harness: caso.py -> deck -> OPM Flow -> score against the logs.

    uv run evaluar.py                       # evaluates caso.py
    uv run evaluar.py --caso otro.py        # evaluates another case file
    uv run evaluar.py --ver-validacion      # the case also sees the log of the held-out well
    uv run evaluar.py > run.log 2>&1        # the way the loop runs it

Prints a block of `key: value` lines after a `---` line. Do not edit this file during the
exercise: the metric has to stay the same for the cases to be comparable.
"""
from __future__ import annotations

import argparse
import dataclasses
import importlib.util
import sys
from pathlib import Path

import numpy as np

from sw import graficar, leer, puntaje
from sw.correr import FlowError, run_flow
from sw.modelo import Case, write_deck
from sw.pozo import WELLS, Cells, load_all

ROOT = Path(__file__).resolve().parent


def load_case(path: Path, cells: Cells) -> Case:
    spec = importlib.util.spec_from_file_location('caso', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    case = module.build(cells)
    if not isinstance(case, Case):
        raise ValueError(f'{path.name}: build() debe devolver un sw.modelo.Case')
    return case.resolved(len(cells))


def initialize(case: Case, cells: Cells, out: Path) -> tuple[np.ndarray, float]:
    """Run Flow and return the initial water saturation per cell and the wall time."""
    seconds = 0.0
    if case.swatinit is not None and np.any(np.isnan(case.swatinit)):
        # Cells without a target saturation take what plain equilibration gives them.
        base = dataclasses.replace(case, swatinit=None, ppcwmax=None)
        seconds += run_flow(write_deck(base, cells, out / 'base'), out / 'base')
        equilibrium = leer.initial_swat(out / 'base', len(cells))
        case = dataclasses.replace(case, swatinit=np.where(np.isnan(case.swatinit), equilibrium, case.swatinit))
    seconds += run_flow(write_deck(case, cells, out), out)
    return leer.initial_swat(out, len(cells)), seconds


def main() -> int:
    ap = argparse.ArgumentParser(description='Evalúa un caso de ajuste contra los perfiles de Volve.')
    ap.add_argument('--caso', type=Path, default=ROOT / 'caso.py')
    ap.add_argument('--salida', type=Path, default=ROOT / 'corridas' / 'ultima')
    ap.add_argument('--sin-grafico', action='store_true')
    ap.add_argument('--ver-validacion', action='store_true',
                    help='el caso también recibe el perfil del pozo de validación (deja de ser una prueba ciega)')
    args = ap.parse_args()

    cells = load_all()
    held_out = [] if args.ver_validacion else [w.name for w in WELLS.values() if w.role == 'validacion']
    try:
        case = load_case(args.caso, cells.hide_sw(held_out))
        sw_sim, seconds = initialize(case, cells, args.salida)
    except (ValueError, FlowError) as e:
        print(f'error: {e}', file=sys.stderr)
        return 1

    result = puntaje.score(cells, sw_sim, case.n_parameters)
    np.savetxt(args.salida / 'sw.csv',
               np.column_stack([cells.md, cells.tvdss, cells.phi, cells.k, cells.sw, sw_sim]),
               delimiter=',', header='md,tvdss,phi,k,sw_perfil,sw_simulado', comments='', fmt='%.5g')
    if not args.sin_grafico:
        figure = graficar.profiles(cells, sw_sim, case, result, args.salida / 'perfil.png')
        print(f'grafico: {figure.relative_to(ROOT) if figure.is_relative_to(ROOT) else figure}')
    print(puntaje.block(case.description, result, seconds))
    print(f'validacion_ciega: {"no" if args.ver_validacion else "si"}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
