"""Fixed harness: caso.py -> deck -> OPM Flow -> score against the logs.

    uv run evaluar.py                       # evaluates caso.py into corridas/ultima/
    uv run evaluar.py --caso casos/j2.py --etiqueta j2
    uv run evaluar.py --fragmento           # also prints the part of the deck the case decides
    uv run evaluar.py --experimento > run.log 2>&1    # the way the loop runs it

With --experimento the run is filed under corridas/exp-NN-<commit>/ together with the commit
message, which is where the loop writes its hypothesis before running. bitacora.py reads those.

Prints a block of `key: value` lines after a `---` line. Do not edit this file during the
exercise: the metric has to stay the same for the cases to be comparable.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

from sw import graficar, leer, puntaje
from sw.correr import FlowError, run_flow
from sw.modelo import Case, fragment, write_deck
from sw.pozo import CONTROL_WELLS, Cells, load_all

ROOT = Path(__file__).resolve().parent


def load_case(path: Path, cells: Cells) -> Case:
    sys.path.insert(0, str(path.resolve().parent))   # a case may import its neighbours
    spec = importlib.util.spec_from_file_location('caso', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    case = module.build(cells)
    if not isinstance(case, Case):
        raise ValueError(f'{path.name}: build() debe devolver un sw.modelo.Case')
    return case.resolved(len(cells))


def initialize(case: Case, cells: Cells, out: Path) -> tuple[np.ndarray, float]:
    """Run Flow and return the initial water saturation per cell and the wall time."""
    seconds = run_flow(write_deck(case, cells, out), out)
    return leer.initial_swat(out, len(cells)), seconds


def git(*args: str) -> str:
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()


def main() -> int:
    ap = argparse.ArgumentParser(description='Evalúa un caso de ajuste contra los perfiles de Volve.')
    ap.add_argument('--caso', type=Path, default=ROOT / 'caso.py')
    ap.add_argument('--etiqueta', default='ultima', help='nombre de la carpeta en corridas/')
    ap.add_argument('--salida', type=Path, help='carpeta de salida; por defecto corridas/<etiqueta>')
    ap.add_argument('--sin-grafico', action='store_true')
    ap.add_argument('--fragmento', action='store_true', help='imprime los AJUSTE_*.INC resumidos')
    ap.add_argument('--experimento', action='store_true',
                    help='archiva la corrida en corridas/exp-NN-<commit>/ con el mensaje del commit')
    args = ap.parse_args()
    commit, message = None, ''
    if args.experimento:
        commit = git('rev-parse', '--short', 'HEAD')
        message = git('log', '-1', '--format=%B')
        number = len(list((ROOT / 'corridas').glob('exp-*'))) + 1
        args.etiqueta = f'exp-{number:02d}-{commit}'
    out = args.salida or ROOT / 'corridas' / args.etiqueta

    cells = load_all()
    try:
        # The control well is never shown to a case.
        case = load_case(args.caso, cells.hide_sw(CONTROL_WELLS))
        sw_sim, seconds = initialize(case, cells, out)
    except (ValueError, FlowError) as e:
        if commit:
            out.mkdir(parents=True, exist_ok=True)
            (out / 'registro.json').write_text(json.dumps(
                {'commit': commit, 'mensaje': message, 'error': str(e), 'hora': time.strftime('%H:%M:%S')},
                ensure_ascii=False, indent=1))
        print(f'error: {e}', file=sys.stderr)
        return 1

    result = puntaje.score(cells, sw_sim, case.n_parameters)
    np.savetxt(out / 'sw.csv',
               np.column_stack([np.arange(len(cells)), cells.md, cells.tvdss, cells.phi, cells.k,
                                cells.net, cells.sw, sw_sim]),
               delimiter=',', header='celda,md,tvdss,phi,k,net,sw_perfil,sw_simulado', comments='', fmt='%.5g')
    (out / 'pozos.txt').write_text('\n'.join(cells.well) + '\n')
    (out / 'fragmento.txt').write_text(fragment(out) + '\n')
    if commit:
        (out / 'registro.json').write_text(json.dumps(
            {'commit': commit, 'mensaje': message, 'caso': case.description, 'fwl': sorted(set(case.fwl)),
             'hora': time.strftime('%H:%M:%S'), **result}, ensure_ascii=False, indent=1))
    if args.fragmento:
        print(fragment(out))
    if not args.sin_grafico:
        figure = graficar.profiles(cells, sw_sim, case, result, out / 'perfil.png')
        print(f'grafico: {figure.relative_to(ROOT) if figure.is_relative_to(ROOT) else figure}')
    print(puntaje.block(case.description, result, case.fwl, seconds))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
